workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: 3.19.0
      groups:
        - macos_credentials
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Fetch Flutter Dependencies
        script: |
          flutter pub get

      - name: Build Unsigned IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - "build/ios/ipa/*.ipa"
